In [1]:
import os
import requests

In [2]:
# Only once -- download the tiny shakespeare dataset:

# input_file_path = os.path.join(os.getcwd(), 'input.txt')
# if not os.path.exists(input_file_path):
#     data_url = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'
#     with open(input_file_path, 'w', encoding='utf-8') as f:
#         f.write(requests.get(data_url).text)

In [3]:
# Read and inspect the data:
with open('input.txt', 'r', encoding = 'utf-8') as f:
    text = f.read()

In [4]:
print('Length of the dataset in characters:', len(text))
# print(text[:1000])

Length of the dataset in characters: 1115394


In [5]:
# Character list:
chars = sorted(list(set(text))) # Sort a list of characters that appear in the text: [, . & .' etc]
vocab_size = len(chars)

print(''.join(chars))
print('Vocabulary size:', vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Vocabulary size: 65


## Tokenize:

In [10]:
# Tokenize: convert raw text (string) to sequence of integers according to some vocabulary of possible elements. 
# Here we translate individual characters (e.g., &) into integers. 

# E.g., Google's using Sentencepiece (not coding whole words nor individual characters - it's sub-word unit level) 
# OpenAI (tiktoken) - example later -. 

# Mapping (look-up table) from characters to integers:
# character : integer and viceversa
stoi = { ch:i for i,ch in enumerate(chars)}
itos = { i:ch for i,ch in enumerate(chars)}

# Encode 
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

In [11]:
print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


#### Example of usage of sub-word encodings (e.g., tiktoken)

In [24]:
import tiktoken
enc = tiktoken.get_encoding('gpt2')
# Vocabulary of GPT2
print('Number of tokens in GPT2', enc.n_vocab)

# Encode - list of integers with values between 0 and 50256 
print('Sentence: "hii there"')
print('Encoding:', enc.encode("hii there"))
# Decode:
print('Decoding:', enc.decode(enc.encode("hii there")))

Number of tokens in GPT2 50257
Sentence: "hii there"
Encoding: [71, 4178, 612]
Decoding: hii there


### Encode the entire tiny shakespeare dataset: 

In [27]:
import torch
# Take all the text in tiny shakespeare, encode it and wrap it into a torch.tensor
data = torch.tensor(encode(text), dtype=torch.long)
# Print the shape and dtype of the tensor
print(data.shape, data.dtype)
# Take a look at the first 1k characters
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

### Split data into train and validation sets

In [28]:
# First 90% will be train:
n = int(0.9*len(data)) 
train_data = data[:n]
val_data = data[n:]

In [39]:
block_size = 8 # i.e., context_lenght 
# First 9 (block_size + 1) characters in the training data. 
train_data[:block_size+1] # 8 individual examples
# that is, in the context of 18 -> 47 comes next; in the context of 18,47 -> 56 comes next, etc. 

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [44]:
x = train_data[:block_size] # Inputs of the transformer (first block size characters)
# e.g., [18, 47, 56, 57, 58,  1, 15, 47]
y = train_data[1:block_size+1] # Next block size characters -- offset by 1 (y are the targets for each position)
# e.g., [47, 56, 57, 58,  1, 15, 47, 58]

for t in range(block_size):
    context = x[:t+1] # All characters in x up to 't', including 't'. 
    target = y[t]
    print(f"when input if {context} the target: {target}")
    
# We train with context between 1 and all the way up to context of block size. 
# We train it this way not just for computational reasons or efficienty but we want the network 
# to be used to see anything in between as little as one to block size. 
# Useful during inference -- we can start sampling generation as little as 1 character of context.
# After blocksize, we truncate 'cause the transformer will never receive more than block size inputs when it's predicting the next character.

when input if tensor([18]) the target: 47
when input if tensor([18, 47]) the target: 56
when input if tensor([18, 47, 56]) the target: 57
when input if tensor([18, 47, 56, 57]) the target: 58
when input if tensor([18, 47, 56, 57, 58]) the target: 1
when input if tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input if tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input if tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


### Dataloader (train the transformer on chunks of data at a time)

In [55]:
# Now, batches of multiple block_size (done for efficiency, parallel processing of data). 

# We sample random locations of the dataset to pull chunks from  
torch.manual_seed(1337) # To reproducte

batch_size = 4 # Number of independent sequences to be processed in parallel
block_size = 8 # Maximum context length for predictions


def get_batch(split):
    # Generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data # Data array
    # Generate random positions to grab a chunk out of -- generate batch_size number of random offsets. 
    ix = torch.randint(len(data) - block_size, (batch_size,)) # 4 numbers (batch_size = 4), randomly generated between 0 and len(data)-block_size
    x = torch.stack([data[i:i+block_size] for i in ix]) # First block_size characters starting at 'i'
    y = torch.stack([data[i+1:i+block_size+1] for i in ix]) # Offset by one of x
    # We get these chunks for every one integer 'i' in ix. Stack 1D tensors as rows: 4x8 tensor. 
    return x, y

# Sample a batch (xb, yb):
xb, yb = get_batch('train')
print('Inputs:', xb.shape)
print(xb) # Each row is an independend chunk of the training set
print('Targets:', yb.shape)
print(yb)

print ('-----------')

print('This [4,8] array contain a total of 32 examples, completely independent: \nthat is, in the context of 24 -> 43 comes next; \nin the context of 24, 43 -> 58 comes next, etc.:')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

Inputs: torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
Targets: torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
-----------
This [4,8] array contain a total of 32 examples, completely independent: 
that is, in the context of 24 -> 43 comes next; 
in the context of 24, 43 -> 58 comes next, etc.:
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [

## Feed

In [56]:
# Input of the transformer: 
print(xb)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [73]:
# Simplest possible NN (Bigram Language Model):
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337) # For reproducibility

class BigramLanguageModel(nn.Module):
    # Subclass of nn.module 
    # Very simple model, tokens are not talking to each other
    
    def __init__(self, vocab_size):
        super().__init__()
        # Each token directly reads off the logitd for the next token from a look-up table
        # Create a token embedding table of size (vocab size, vocab size): 
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, idx, targets=None):
        # inputs and targets are passed to the token embedding table
        # e.g., number 24 in xb will plug out the 24th row of the embedding table, number 43 will do the same for 43rd row, etc. 
        # idx and targets are both (B, T) tensor of integers
        # (Batch, Time, Channel) -- (batch_size, block_size, vocab_size) = (4, 8, 64)
        logits = self.token_embedding_table(idx) # (B, T, C) -- Scores for the next character of the sequence -- we're predicting based on the identity of a single token
        
        if targets is None:
            loss = None
        else:
            # Good way to measure the loss or the quality of the predictions is to use the negative log-likelohood (cross-entropy) 
            # Torch expects the channel to be the 2nd dimension -> (B, C, T), so reshape
            B, T, C = logits.shape # (4, 8, 64)
            logits = logits.view(B*T, C) # (4x8, 64)
            # Targets are (B, T):
            targets = targets.view(B*T) # or (-1), size (4x9)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is the current context of some characters in some batch
        # idx is (B, T) array -- e.g., (4, 8)
        
        # Note that this function gets fed with the full idx to predict a single character at a time. 
        # it is only necessary, for predicting the next character, to know the previous one.
        # in line logits[:, -1, :], we're only using the last one instead of the whole history. 
        # so far, no needed. later history will be used. 
        
        # Generate data from the model
        for _ in range(max_new_tokens):
            # Get te predictions for the current idx
            logits, loss = self(idx)
            # Focus only on the last time step
            # logits are (B, T, C) --> convert them to (B, C) 
            # taking the last time-step, as those are the predictions of what comes next.
            logits = logits[:, -1, :] # (B, C)
            # Apply softmax to convert logits to probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # Sample from the probability distribution, give 1 sample (integer)
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1), for each of the batch dimension, we get a single prediction of what comes next. 
            
            # Append sampled index to the running sequence: 
            # whatever is predicted, is concatenated on top of the previous idx along 
            # the first dimension (time dimension) to get (B, T+1)
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1) e.g., -- (4,9) 
        return idx
    
    
# vocab_size = len(chars) characters
m = BigramLanguageModel(vocab_size)
# Passing it the inputs and targets to BLM
# Scores for the next character of the sequence
logits, loss = m(xb, yb)
print(logits.shape)
# We have 65 possible vocab elements, we can guess what the loss should be -- negative log-likelihood : -ln(1/65) = 4.17
print(loss)

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)


In [76]:
idx = torch.zeros((1,1), dtype=torch.long) # (B=1, T=1) dtype int
# (m.generate)[0] to umplug 
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))


KuBZvrpxZQgC-hlkq,ptKqHoiX-jjeLJ &slERj KUsBOL!mpJO!zLg'wNfqHAMgq'hZCWhu.W.IBcP 
RFJ&DEs,nw?pxE?xjNH


## Train

In [77]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3) # takes parameters and updates the gradients

In [85]:
batch_size = 32

for steps in range(10000):
    
    # Get a batch of data from the data loader
    xb, yb = get_batch('train')
    
    # Evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True) # Zeroing the gradients from the previous step 
    loss.backward() # get the gradients from all the parameters
    optimizer.step() # use the gradients to update 
    
print(loss.item())
    

2.443098783493042


In [88]:
idx = torch.zeros((1,1), dtype=torch.long) # (B=1, T=1) dtype int
# (m.generate)[0] to umplug 
print(decode(m.generate(idx, max_new_tokens=500)[0].tolist()))



INo ompe Pe o m P: somistrou, paburoinsee
Londer wathes 's, mayousorntekeawhart ghruremin whell y angr hinnds oupre hingo, foune:
s hase!
NS:
Stho lereer atiswouese?


He'cindine u'sold ngnfithot pon d te;
Whie roomy t'd ING ELABe ofulin blakl ttr fr s fe
JUn bowid t s r-jure
My avinoursouen te, stht mas t fos.
W:
Inouim s sely loreny goulavir Rie, ak shas askngef e, nghin housuly ot ont armame.
Hel o ppe? mosisigherde w; s tsere cof oubre pl lothes

t re ice'Sat thercorjut nthet, t ey t t:

BE


# Self-attention

In [115]:
# toy example:
torch.manual_seed(1337)
B, T, C = 4, 8, 2 # Batch size, time (number of tokens, context length), channels (length of the character list)
x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

   The tokens in the batch (8) are currently not talking to each other - and we owuld like to couple them. We want to couple them in a specific way: token in the 5th should NOT communicate with tokens in the 6th, 7th and 8th, those are future tokens in the sequence.

   The token in the 5th location should only talk to the tokens in the 4th, 3rd, 2nd and 1st locations. 
    
   Information only flows from previous context to the current time step (curent token). 

   Easiest way to communicate -- very weak -- we lose spatial info about the spatial arrangement of the tokens: 
    take average of all the preceding elements; e.g., for 5th token take the channels C that make up info at my step for time steps 4, 3, 2 and 1.  
    
   For every single batch element, independently: for every t token in that sequence, calculate the avg of all the vectors in all the previous token and also at t token.

In [116]:
# We want x[b,t] = mean_{i<=t} x[b,i]
# bag of words (bow), averaging. 
xbow = torch.zeros((B,T,C))

# Version 1: very inefficient! 
for b in range(B): # for each batch
    for t in range(T): # for each token in the sequence
        # previous tokens are at batch dimension 'b', and everything up to (and including) the 't' token
        xprev = x[b,:t+1] # (t, C)
        # avg / mean over the time dimension 
        xbow[b,t] = torch.mean(xprev, 0)

In [111]:
x[0], xbow[0] # 1st one is itself, 2nd one is the avg of the first 2, etc -- last one is the vertical avg of all the previous ones. 

(tensor([[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))

In [112]:
# Version 2: Efficient using matmul:
# torch.manual_seed(42)
# a = torch.tril(torch.ones(3,3))
# a = a / torch.sum(a, 1, keepdim=True)
# b = torch.randint(0,10,(3,2)).float()
# c = a @ b

# print('a=')
# print(a)
# print('b=')
# print(b)
# print('------')
# print('Avg of the rows: c=')
# print(c)

In [124]:
# Version 2: Weighted sums, the weights are specified in wei -- triangular form ensures that the token at the 't' position
# only gets info from the previous locations. 
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x  # apply it in parallel for the batches B (B, T, T) @ (B, T, C) --> (B, T, C)
# torch.allclose(xbow, xbow2)

In [127]:
# Version 3: using softwax
tril = torch.tril(torch.ones(T, T)) 

wei = torch.zeros((T,T)) # affinities between tokens -- now set at zero, but they're going to be data dependent!
# -- depending on what their values are, some tokens will find other tokens more/less interesting

# masked fill -- for all the elements where tril ==0, make them being -inf.
# tokens from the future cannot communicate -- setting them to -inf.
wei = wei.masked_fill(tril ==0, float('-inf'))
# softmax on each row -- normalization operation: exp(elements) / sum 
# e.g., [1, 0, 0, 0, 0, 0, 0, 0] / 1 = [1, 0, ...]
# e.g., [1, 1, 0, 0, 0, 0, 0, 0] / 2 = [0.5, 0.5, 0, ...]
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
# torch.allclose(xbow, xbow3)

### Version 4: self-attention!



**Self-attention mechanism:**

Every single token, at each position, will emit 2 vectors (query and key). 

    Query - what am i looking for?

    Key - what do i contain?

Affinities between the tokens in a sequence, we do the dot product between keys and queries:

    my query - dot products - with all the keys of other tokens -> this will become the wei value.
    
If the key and the query are sort of aligned, they will interact to a very high amount -- get to learn more about that specific token as opposed to any other token in the sequence.

In [149]:
torch.manual_seed(1337)
B, T, C = 4, 8, 32 # batch, time, channels -> 4 batches of 8 tokens the information of each is 32 dimensional
x = torch.randn(B, T, C)


# Single Head perform self-attention
head_size = 16 # 
key = nn.Linear(C, head_size, bias=False) # Apply matmul with fixed weights (bias is False).
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
# All tokens in x produce, independently and in parallel, a key and query values. No communication between them. 
k = key(x) # (B, T, 16) 
q = query(x) # (B, T, 16)
v = value(x) # Thing that gets aggregrated (the information) 

wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) --> (B, T, T); 
# for every row of B, we have a T square matrix giving us the affinities. 

tril = torch.tril(torch.ones(T,T))
# wei = torch.zeros((T,T)) # Affinities (i.e., nodes)
wei = wei.masked_fill(tril ==0, float('-inf')) # Not allowed to comminucate with future tokens
wei = F.softmax(wei, dim=-1) # Exponentiate and normalize (all positive)
# out = wei @ x
out = wei @ v
out.shape

torch.Size([4, 8, 16])

In [150]:
# Every single batch element contains different tokens and postions, so each one gets a different wei value. 
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [147]:
# Scaled attention: IMPORTANT! -- used to control the variance at normalization. 
#From attention is all you need (eq.1). 
# attention = softmax(Q*K_transposed / sqrt(head size))*V

#Example
k = torch.randn(B, T, head_size)
q = torch.randn(B, T, head_size)

wei = q @ k.transpose(-2,-1) * head_size**-0.5

k.var(), q.var(), wei.var() # var=1, is preserved. 
# it is very important - specially during initialization - that wei is fairly diffused. 
# If wei is not fairly diffused, it will converge to one-hot vectors. 

In [154]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)
# we get a diffused result

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [156]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)
# softmax sharps towards the maximum -- we don't want the values to be too extreme. 

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])